name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests jsonschema

    - name: Validate JSON syntax
      run: |
        python validate_json.py

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event.action != 'closed'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Deploy to Cloudflare
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: |
        python deploy.py

  delete:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Delete from Cloudflare
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: |
        python delete.py
